### ISSUE TITLE
Lunar/Solar eclipse events

### ISSUE THREAD

**Issue by Dster5** [TheAGamePlayer/The-Pure-Suffering-Mod#1]
I think that it would be pretty cool if there was something in the commons that would allow you to modify the Lunar and solar eclipses, imagine if you could have a Lunar or Solar eclipse every night for an extra challenge, not that would be true pure suffering.

**Comment by TheAGamePlayer** [comment]
I plan to make the mod way more configurable in the next update, I will see about making perpetual eclipses a possibility :>

**Comment by TheAGamePlayer** [comment]
1.2.0B is now released meaning perpetual eclipses are now possible. By adding "puresuffering:solar_eclipse" & "puresuffering:lunar_eclipse" to the primaryWhitelist config list, changing the tieredInvasions config option to false, setting consistentInvasions to true, and changing the dayInvasionRarity and the nightInvasionRarity to 0, you can now achieve eclipses every day and night.
