### ISSUE TITLE
Mod crashes on server

### ISSUE THREAD

**Issue by Byllfighter** [TheAGamePlayer/The-Pure-Suffering-Mod#10]
The mod started crashing after restarting the server.

[latest.log](https://github.com/TheAGamePlayer/The-Pure-Suffering-Mod/files/13859321/latest.log)

**Comment by TheAGamePlayer** [comment]
Sorry for the late response, I am going to release 1.6.0.3R to fix this problem. It would seem that the crash of one mod led to the crash of my mod, but the new update should allow you to confirm it.

**Comment by TheAGamePlayer** [comment]
Going to mark this issue as solved for now, but please reopen the issue if you find that the problem still exists in the new version.
