### ISSUE TITLE
Server crash becasue of null event

### ISSUE THREAD

**Issue by EthanFields** [TheAGamePlayer/The-Pure-Suffering-Mod#11]
[crash-2024-02-16_14.16.21-server.txt](https://github.com/TheAGamePlayer/The-Pure-Suffering-Mod/files/14316643/crash-2024-02-16_14.16.21-server.txt)

mod crashes server, event null?

**Comment by TheAGamePlayer** [comment]
Looking at the crash report with my code, It would seem that an entity attempted to convert into another entity, but there wasn't an entity type that it could convert into. I will release 1.6.0.4 with a couple safety precautions to prevent this from happening in the future.

**Comment by TheAGamePlayer** [comment]
I have released 1.6.0.4R for 1.20.1 and will be releasing 1.6.1.1R for 1.20.2. Let me know if this is fixed for you in the new version before I close :)
