### ISSUE TITLE
Mod keeps crashing my server

### ISSUE THREAD

**Issue by haeihaiehaei** [TheAGamePlayer/The-Pure-Suffering-Mod#3]
Hi, not 100% sure but I think this mod keeps crashing my server running my own modpack, heres the crash log:

https://pastebin.com/kNi4Wz6f

**Comment by TheAGamePlayer** [comment]
After looking into this for about an hour, there is a bug where the random chance for canceling an invasion will crash the server, I will be releasing 1.2.1B later today to fix this.

**Comment by TheAGamePlayer** [comment]
1.2.1B is now released and should fix this bug. If the bug persists let me know, otherwise I shall close this issue in a few days.

**Comment by haeihaiehaei** [comment]
Thanks dude, will try it out and let you know!

**Comment by haeihaiehaei** [comment]
Had no more issues since updating, thanks for the help :)
