### ISSUE TITLE
Crash on Invasion Start (1.16.5) also to be fixed on (1.18.2)(1.19.3)

### ISSUE THREAD

**Issue by Yuogusy** [TheAGamePlayer/The-Pure-Suffering-Mod#6]
I have a similar issue as reported in another issue report for 1.18.2 here: https://github.com/TheAGamePlayer/The-Pure-Suffering-Mod/issues/5

It causes a crash report that is very similar: https://pastebin.com/wfMkwKR4

I noticed that you mentioned that that particular issue might be related to 1.18 chunk loading, so this might not be related, but it looks quite similar. Much like his issue, I cannot reload the game until I disable the mod.

I am on Forge 36.2.39 (Minecraft 1.16.5). I have not tried an older version as of yet, and am on Pure Suffering 1.3.1R, the newest on CurseForge.

Thank you!

**Comment by TheAGamePlayer** [comment]
It seems that I only fixed part of the problem, while mobs can no longer spawn in unloaded chunks with the bug fix, the bug still remains as a client-server desync occurs when a player is about to disconnect from the server. The mod attempts to find a player before deciding where it should spawn mobs, but if the player is disconnected and the world is still loaded, it can lead to a crash bricking the world. I will be releasing an update on 1.16.5, 1.18.2, and 1.19.3 to fix this.

**Comment by TheAGamePlayer** [comment]
I just uploaded bug fixes on all 3 versions to CurseForge, in my test world it fixed the problem. Let me know if it does the same for you before I close the issue ;)

**Comment by Yuogusy** [comment]
It works perfectly, been testing all day. Thank you!

**Comment by TheAGamePlayer** [comment]
Thank you for letting me know :)
