### ISSUE TITLE
I'm having some issues with armor stands.

### ISSUE THREAD

**Issue by Wafer6** [TheAGamePlayer/The-Pure-Suffering-Mod#9]
I don't know if this works for you.

https://crashy.net/03dee5e2-30b2-4306-a656-d7ac3f556380

**Comment by TheAGamePlayer** [comment]
I am aware of this bug, I am finishing 1.5.0.0R with numerous bug fixes and new features. I will attempt to release this asap, I am aiming for a release date today.

**Comment by TheAGamePlayer** [comment]
This bug is now fixed as of 1.5.0.0R, now updated on Curseforge!
